universe = vanilla

executable          = sendJob.sh
arguments           = $(Cluster) $(Process)

log                 = test.log
output              = outfile.$(Cluster).$(Process).out
error               = errors.$(Cluster).$(process).err

request_Cpus        = 4
request_Gpus        = 1
#request_Memory      = 4000

queue 1
#queue arguments from MyFile_ttbar.txt
#queue arguments in (tHq, ttbar, ttW, Diboson, tZq)