universe = vanilla

executable          = sendJob_dilepOStau.sh
arguments           = $(Cluster) $(Process)

log                 = condoroutputs_GA/log/$(Cluster).$(Process).log
output              = condoroutputs_GA/output/$(Cluster).$(Process).out
error               = condoroutputs_GA/error/$(Cluster).$(process).err


request_Cpus        = 4
request_Gpus        = 1
request_Memory      = 4000

queue 1
