universe = vanilla

#executable          = sendJob_dilepOStau.sh
executable          = sendJob_dilepOStau_LOAD_syst.sh
arguments           = $(Cluster) $(Process)

log                 = condoroutputs/log/$(Cluster).$(Process).log
output              = condoroutputs/OS_output/$(Cluster).$(Process).out
error               = condoroutputs/OS_error/$(Cluster).$(process).err


request_Cpus        = 4
request_Gpus        = 1
request_Memory      = 4000

queue arguments from ListOfSystematics_3.txt
